export const translations = {
  'pt-BR': {
    repeatsMonthly: 'Isso se repete todo mês?', dayOfMonth: 'Dia do mês', autoConfirm: 'Confirmar automaticamente no dia', firstOccurrenceHelp: 'Este lançamento será confirmado agora. Os próximos seguirão o dia escolhido.', monthlyFlow: 'Rotina do mês', recurringFor: 'Recorrências · {period}', pendingCountOne: '1 pendente', pendingCountMany: '{count} pendentes', confirmAmount: 'Valor para confirmar', confirmOccurrence: 'Confirmar', skipOccurrence: 'Pular', confirmedAutomatically: 'Confirmado automaticamente', adjustAmount: 'Ajustar valor', undoAutoConfirm: 'Desfazer', undoAutoConfirmQuestion: 'Desfazer a confirmação automática e remover este lançamento?', noPendingRecurrences: 'Nenhuma recorrência pendente neste mês.', manageRecurringRules: 'Gerenciar recorrências', noRecurringRules: 'Ainda não há recorrências.', monthlyDay: 'dia {day}', activeRule: 'Ativa', inactiveRule: 'Inativa', endsOn: 'Termina em (opcional)', deactivateRule: 'Desativar', reactivateRule: 'Reativar', recurringCreated: 'Recorrência criada e primeiro lançamento confirmado.', occurrenceConfirmed: 'Recorrência confirmada.', occurrenceSkipped: 'Recorrência pulada.', occurrenceAdjusted: 'Valor ajustado.', autoConfirmationUndone: 'Confirmação desfeita.', ruleUpdated: 'Recorrência atualizada.', recurringActionError: 'Não foi possível atualizar a recorrência.', recurringEntryInUse: 'Este lançamento pertence a uma recorrência. Ajuste ou desfaça pela seção de recorrências.',
    records: 'Lançamentos', newEntry: 'Novo lançamento', entryType: 'Tipo', expenseType: 'Despesa', incomeType: 'Ganho', allEntries: 'Todos os lançamentos', noEntries: 'Nenhum lançamento encontrado.', editIncome: 'Editar ganho', addIncome: 'Adicionar ganho', expenseDate: 'Data da despesa', receivedDate: 'Data do recebimento', incomeDescriptionExample: 'Ex: Salário ou bônus', deleteIncomeConfirm: 'Deseja excluir este ganho?', incomeCreated: 'Ganho adicionado.', incomeUpdated: 'Ganho atualizado.', incomeDeleted: 'Ganho excluído.', incomeDeleteError: 'Não foi possível excluir o ganho.', totalReceived: 'Recebido em {period}', netBalance: 'Saldo em {period}',
    manageCategories: 'Gerenciar categorias', categoryHelp: 'Personalize nomes e cores. Categorias usadas em despesas ou recorrências não podem ser excluídas.', categoryName: 'Nome da categoria', categoryColor: 'Cor da categoria', newCategory: 'Nova categoria', addCategory: 'Adicionar categoria', deleteCategoryConfirm: 'Excluir a categoria {name}?', categoryCreated: 'Categoria adicionada.', categoryUpdated: 'Categoria atualizada.', categoryDeleted: 'Categoria excluída.', categoryInUse: 'Esta categoria tem despesas ou recorrências vinculadas. Ajuste-as antes de excluí-la.', categorySaveError: 'Não foi possível salvar a categoria.', categoryDeleteError: 'Não foi possível excluir a categoria.',
    dashboard: 'Visão geral', expenses: 'Despesas', logout: 'Sair', lightMode: 'Ativar modo claro', darkMode: 'Ativar modo escuro', language: 'Idioma',
    welcome: 'Bem-vindo de volta', welcomeSubtitle: 'Entre na sua conta para continuar', email: 'E-mail', password: 'Senha', signIn: 'Entrar', signingIn: 'Entrando...', noAccount: 'Não tem conta?', signUp: 'Cadastre-se',
    createAccount: 'Criar conta', createSubtitle: 'Comece a cuidar das suas finanças hoje', name: 'Nome', yourName: 'Seu nome', minPassword: 'Mínimo 8 caracteres', confirmPassword: 'Confirmar senha', repeatPassword: 'Repita a senha', creatingAccount: 'Criando conta...', haveAccount: 'Já tem conta?',
    overviewKicker: 'Seu panorama', recordsKicker: 'Seus registros', totalSpent: 'Total gasto em {period}', byCategory: 'Gastos por categoria', lastSixMonths: 'Últimos 6 meses',
    newExpense: 'Nova despesa', editExpense: 'Editar despesa', category: 'Categoria', allCategories: 'Todas', month: 'Mês', allMonths: 'Todos', year: 'Ano', allYears: 'Todos', clearFilters: 'Limpar filtros', noExpenses: 'Nenhuma despesa encontrada.', noExpensesMonth: 'Nenhuma despesa neste mês.', noChartData: 'Nenhum dado disponível.',
    date: 'Data', description: 'Descrição', amount: 'Valor', amountBrl: 'Valor (R$)', actions: 'Ações', edit: 'Editar', delete: 'Excluir', deleteConfirm: 'Deseja excluir esta despesa?', chooseCategory: 'Selecione...', descriptionExample: 'Ex: Almoço no restaurante', cancel: 'Cancelar', saveChanges: 'Salvar alterações', add: 'Adicionar', saving: 'Salvando...',
    loading: 'Carregando...', loadError: 'Erro ao carregar dados.', genericError: 'Ocorreu um erro. Tente novamente.', invalidField: 'Confira este campo e tente novamente.', invalidCredentials: 'E-mail ou senha incorretos.', created: 'Despesa adicionada.', updated: 'Despesa atualizada.', deleted: 'Despesa excluída.', deleteError: 'Não foi possível excluir a despesa.',
    catFood: 'Alimentação', catTransport: 'Transporte', catHousing: 'Moradia', catHealth: 'Saúde', catLeisure: 'Lazer', catOther: 'Outros',
  },
  en: {
    repeatsMonthly: 'Does this repeat every month?', dayOfMonth: 'Day of month', autoConfirm: 'Confirm automatically on the due day', firstOccurrenceHelp: 'This entry will be confirmed now. Future entries will use the selected day.', monthlyFlow: 'Monthly rhythm', recurringFor: 'Recurrences · {period}', pendingCountOne: '1 pending', pendingCountMany: '{count} pending', confirmAmount: 'Amount to confirm', confirmOccurrence: 'Confirm', skipOccurrence: 'Skip', confirmedAutomatically: 'Confirmed automatically', adjustAmount: 'Adjust amount', undoAutoConfirm: 'Undo', undoAutoConfirmQuestion: 'Undo automatic confirmation and remove this entry?', noPendingRecurrences: 'No pending recurrences this month.', manageRecurringRules: 'Manage recurrences', noRecurringRules: 'No recurrences yet.', monthlyDay: 'day {day}', activeRule: 'Active', inactiveRule: 'Inactive', endsOn: 'Ends on (optional)', deactivateRule: 'Deactivate', reactivateRule: 'Reactivate', recurringCreated: 'Recurrence created and first entry confirmed.', occurrenceConfirmed: 'Recurrence confirmed.', occurrenceSkipped: 'Recurrence skipped.', occurrenceAdjusted: 'Amount adjusted.', autoConfirmationUndone: 'Confirmation undone.', ruleUpdated: 'Recurrence updated.', recurringActionError: 'Could not update the recurrence.', recurringEntryInUse: 'This entry belongs to a recurrence. Adjust or undo it in the recurrence section.',
    records: 'Transactions', newEntry: 'New transaction', entryType: 'Type', expenseType: 'Expense', incomeType: 'Income', allEntries: 'All transactions', noEntries: 'No transactions found.', editIncome: 'Edit income', addIncome: 'Add income', expenseDate: 'Expense date', receivedDate: 'Date received', incomeDescriptionExample: 'E.g. Salary or bonus', deleteIncomeConfirm: 'Delete this income?', incomeCreated: 'Income added.', incomeUpdated: 'Income updated.', incomeDeleted: 'Income deleted.', incomeDeleteError: 'Could not delete the income.', totalReceived: 'Received in {period}', netBalance: 'Balance in {period}',
    manageCategories: 'Manage categories', categoryHelp: 'Customize names and colors. Categories used by expenses or recurrences cannot be deleted.', categoryName: 'Category name', categoryColor: 'Category color', newCategory: 'New category', addCategory: 'Add category', deleteCategoryConfirm: 'Delete the {name} category?', categoryCreated: 'Category added.', categoryUpdated: 'Category updated.', categoryDeleted: 'Category deleted.', categoryInUse: 'This category is linked to expenses or recurrences. Update them before deleting it.', categorySaveError: 'Could not save the category.', categoryDeleteError: 'Could not delete the category.',
    dashboard: 'Overview', expenses: 'Expenses', logout: 'Log out', lightMode: 'Switch to light mode', darkMode: 'Switch to dark mode', language: 'Language',
    welcome: 'Welcome back', welcomeSubtitle: 'Sign in to continue', email: 'Email', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in...', noAccount: 'New here?', signUp: 'Create an account',
    createAccount: 'Create an account', createSubtitle: 'Start taking care of your finances today', name: 'Name', yourName: 'Your name', minPassword: 'At least 8 characters', confirmPassword: 'Confirm password', repeatPassword: 'Repeat your password', creatingAccount: 'Creating account...', haveAccount: 'Already have an account?',
    overviewKicker: 'Your picture', recordsKicker: 'Your records', totalSpent: 'Total spent in {period}', byCategory: 'Spending by category', lastSixMonths: 'Last 6 months',
    newExpense: 'New expense', editExpense: 'Edit expense', category: 'Category', allCategories: 'All', month: 'Month', allMonths: 'All', year: 'Year', allYears: 'All', clearFilters: 'Clear filters', noExpenses: 'No expenses found.', noExpensesMonth: 'No expenses this month.', noChartData: 'No data available.',
    date: 'Date', description: 'Description', amount: 'Amount', amountBrl: 'Amount (BRL)', actions: 'Actions', edit: 'Edit', delete: 'Delete', deleteConfirm: 'Delete this expense?', chooseCategory: 'Choose a category...', descriptionExample: 'E.g. Lunch at a restaurant', cancel: 'Cancel', saveChanges: 'Save changes', add: 'Add expense', saving: 'Saving...',
    loading: 'Loading...', loadError: 'Could not load data.', genericError: 'Something went wrong. Please try again.', invalidField: 'Check this field and try again.', invalidCredentials: 'Incorrect email or password.', created: 'Expense added.', updated: 'Expense updated.', deleted: 'Expense deleted.', deleteError: 'Could not delete the expense.',
    catFood: 'Food', catTransport: 'Transport', catHousing: 'Housing', catHealth: 'Health', catLeisure: 'Leisure', catOther: 'Other',
  },
}

export const categoryKeys = { 'Alimentação': 'catFood', Transporte: 'catTransport', Moradia: 'catHousing', 'Saúde': 'catHealth', Lazer: 'catLeisure', Outros: 'catOther' }
